apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- with .Values.additionalServicePorts }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
